[package]
name = "wrs"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.24.0", features = [ "derive" ] }
cgmath = "0.18.0"
env_logger = "0.11.8"
pollster = "0.4.0"
rust-fontconfig = "1.0.3"
wgpu = "27.0.1"
winit = "0.30.12"
